use UNIVER;

--select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
--from GROUPS
--inner join FACULTY on GROUPS.FACULTY = FACULTY.FACULTY
--inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
--inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
--where FACULTY.FACULTY like 'ХТиТ'
--group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY like 'ХТиТ'
group by cube (GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY)