use UNIVER;

--select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
--from GROUPS
--inner join FACULTY on GROUPS.FACULTY = FACULTY.FACULTY
--inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
--inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
--where FACULTY.FACULTY like 'ХТиТ'
--group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2)
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where FACULTY.FACULTY = 'ХТиТ'
group by rollup(GROUPS.PROFESSION, PROGRESS.SUBJECT), FACULTY.FACULTY
