use UNIVER;

select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
union
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
union all
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,  round(avg(cast(NOTE AS float(1))), 2) as [Средняя оценка]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY