use BANK

CREATE TABLE [dbo].[Owner] (
[FIO] NVARCHAR (35) NOT NULL,
[birthDate] DATETIME NOT NULL,
[phoneNumber] NVARCHAR (22) NULL,
[wallet] NVARCHAR (4) NULL,
[passportInfo] NCHAR (10) NOT NULL,
PRIMARY KEY CLUSTERED ([FIO] ASC)
);


CREATE TABLE [dbo].[PersonalBill] (
[Id] INT IDENTITY (11000, 1) NOT NULL,
[FIO] NVARCHAR (35) NOT NULL,
[sendDate] DATETIME NULL,
[startBalance] INT NULL,
[town] NVARCHAR (20) NOT NULL,
[services] NVARCHAR (50) NULL,
CONSTRAINT [PK__Personal__3214EC071237FB30] PRIMARY KEY CLUSTERED ([Id] ASC),
CONSTRAINT [FK__PersonalBil__FIO__267ABA7A] FOREIGN KEY ([FIO]) REFERENCES [dbo].[Owner] ([FIO])
);