SELECT *
FROM dbo.STUDENT FULL OUTER JOIN dbo.PROGRESS
ON dbo.STUDENT.IDSTUDENT = dbo.PROGRESS.IDSTUDENT
WHERE SUBJECT is NULL


SELECT *
FROM dbo.AUDITORIUM FULL OUTER JOIN dbo.AUDITORIUM_TYPE
ON dbo.AUDITORIUM.AUDITORIUM_TYPE = dbo.AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM is NULL


SELECT *
FROM dbo.AUDITORIUM FULL OUTER JOIN dbo.AUDITORIUM_TYPE
ON dbo.AUDITORIUM.AUDITORIUM_TYPE = dbo.AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE is NULL and AUDITORIUM_TYPE.AUDITORIUM_TYPE is null