use UNIVER;

select AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
from AUDITORIUM aud1
where AUDITORIUM_CAPACITY = (select top(1) AUDITORIUM_CAPACITY from AUDITORIUM aud2
	where aud2.AUDITORIUM_TYPE = aud1.AUDITORIUM_TYPE
order by AUDITORIUM_CAPACITY desc)

select AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
from AUDITORIUM aud1