use UNIVER;

select * from AUDITORIUM

select  AUDITORIUM.AUDITORIUM_TYPE, 
	MAX(AUDITORIUM_CAPACITY)[Макс. вместимость],
	MIN(AUDITORIUM_CAPACITY)[Мин. вместимость],
	AVG(AUDITORIUM_CAPACITY)[Средн. вместимость],
	SUM(AUDITORIUM_CAPACITY)[Сумм. вместимость],
	COUNT(AUDITORIUM_CAPACITY)[Кол-во аудиторий]
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
group by AUDITORIUM.AUDITORIUM_TYPE
