use UNIVER;

select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY, AVG(PROGRESS.NOTE) AS [Средняя оценка]
from GROUPS
inner join FACULTY on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where FACULTY.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY